MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "mv2_72.5.pth"
  BACKBONE:
    CONV_BODY: "MV2-FPN"
  MOBILENET:
    BACKBONE_OUT_CHANNELS: 256
    OUT_CHANNELS: (144, 192, 384, 960)
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("wider_trainval",)
  TEST: ("wider_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (80000, 100000)
  MAX_ITER: 120000
